name: flyt_app
description: "Flyt Trip Planner"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Remote Data Source
  #  dio: ^5.4.1
  #  http: ^1.2.2
  #  retrofit: ^4.1.0
  #  retrofit_generator: ^8.1.0
  #  json_annotation: ^4.8.1
  #  json_serializable: ^6.7.1
  intl: ^0.20.2

  # Build Generator
  build_runner: ^2.4.11

  # Shared Preferences
  shared_preferences: ^2.2.2

  # Hive Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1

  # Dependency Injection
  get_it: ^7.6.7

  # Path Provider
  path_provider: ^2.1.2
  provider: ^6.1.1

  # Bloc State Management
  flutter_bloc: ^8.1.4

  # For Testing Class
  equatable: ^2.0.5

  # UUID
  uuid: ^4.5.1

  # Flutter SVG
  flutter_svg: ^2.2.0

  # Flutter TTS
  flutter_tts: ^4.2.3

  # Image Picker
  image_picker: ^1.0.7

  # Image
  image: ^4.5.4

  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.14.4"

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.otf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/poppins/Poppins-Medium.otf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.otf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.otf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.otf
          weight: 800
  assets:
    - assets/svg/packing.svg
    - assets/svg/phrases.svg
    - assets/svg/traveler.svg
    - assets/svg/trip.svg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21